const dataFromServer = [
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Andrew",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Bob",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Karl",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Pitt",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
  {
    id: 101,
    firstName: "Sue",
    lastName: "Corson",
    email: "DWhalley@in.gov",
    phone: "(612)211-6296",
    address: {
      streetAddress: "9792 Mattis Ct",
      city: "Waukesha",
      state: "WI",
      zip: "22178",
    },
    description: "et lacus magna dolor...",
  },
];

export  default dataFromServer;